version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n_db
      DB_POSTGRESDB_USER: duane
      DB_POSTGRESDB_PASSWORD: duane_password
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin123
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_TUNNEL_URL: http://localhost:5678
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network

volumes:
  n8n_data:

networks:
  n8n_network:
    external: true
